import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const token = readFileSync('C:/Users/Aochi/AppData/Local/Temp/tok2', 'utf8').trim();
const [out, w, path] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: Number(w), height: 900 } });
await page.addInitScript((t) => localStorage.setItem('soumetsu.token', t), token);
await page.goto('http://localhost:5173' + path, { waitUntil: 'networkidle' });
await page.locator('.pager').scrollIntoViewIfNeeded();
await page.waitForTimeout(500);
await page.locator('.pager').screenshot({ path: out });
await browser.close();
